### ISSUE TITLE
Opens Zeronet in default browser

### ISSUE THREAD

**Issue by kustomzone** [kustomzone/Fuzium#1]
Not supposed to open in browser, but since the app doesn't yet detect **new** (copied) zites in the data folder then this is one way to add new zites (by using the address bar of whichever browser you normally use)

**Comment by HelloZeroNet** [comment]
Starting it with `zeronet.exe --open_browser ""` should work.

**Comment by kustomzone** [comment]
Yep, that worked. Cheers.
