### ISSUE TITLE
The title of NW.js creator in the README is incorrect

### ISSUE THREAD

**Issue by GnorTech** [kustomzone/Fuzium#2]
The title of NW.js creator in the README is incorrect. node-webkit and NW.js creator Roger wrote a statement about this. See the full story here: https://groups.google.com/d/msg/nwjs-general/LIrC7zHtQdo/6Gd5MXVsCAAJ

**Comment by kustomzone** [comment]
Thanks for pointing this out. I only read Zhao Cheng's posts the day before yesterday for the first time. I know Roger Wang continues to work diligently on NW.js, and his new post explains the prior involvement of himself and others quite well.

I could change it to co-creator, but for now it's probably enough to remove mention of NW.js, though it was mainly my intention of letting people know there was prior connection between both projects from the beginning. The link to Cheng's site and your link to Roger's post have done that. Cheers.
